-- | Test entry point.
--
-- hspec-discover automatically generates the 'main' function from this file at
-- compile time (via the @-F -pgmF hspec-discover@ pragma below).  It scans all
-- directories on the @hs-source-dirs@ path for files whose name ends in
-- @Spec.hs@ and wires them into a single 'hspec' run.
--
-- To add a new test module, create a file named @FooSpec.hs@ anywhere under
-- @test/@ that exports a @spec :: Spec@ value.  hspec-discover picks it up
-- automatically — no changes to this file are needed.
{-# OPTIONS_GHC -F -pgmF hspec-discover #-}
