name: Cyclomatic Complexity

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  homplexity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.8.2'
          cabal-version: '3.10.3.0'
      - name: Install homplexity
        run: cabal install homplexity
      - name: Run homplexity check
        run: homplexity src app test Examples