name: Formatting

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  fourmolu:
    # Temporarily disabled: run locally instead for fast feedback.
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.8.2'
          cabal-version: '3.10.3.0'
      - name: Install fourmolu
        run: cabal install fourmolu
      - name: Run fourmolu check
        run: fourmolu --mode check $(find src app test Examples -name "*.hs")