name: Mutation Analysis

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  mutation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.8.2'
          cabal-version: '3.10.3.0'
      - name: Run test suite
        run: cabal test all --test-show-details=direct
      - name: Build mucheck
        run: cabal build all --write-ghc-environment-files=always
      - name: Run mutation tests with MSI quality gate
        run: cabal run mucheck -- --min-msi 50 --ignore-msi-with-no-mutations Examples/AssertCheckTest.hs